//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "build_reports")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub drv_path: Option<String>,
    pub output_name: Option<String>,
    pub store_path_hash: String,
    pub store_path: String,
    pub nar_hash: String,
    pub nar_size: i64,
    pub cache_url: Option<String>,
    pub created_at: DateTime,
    pub user_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
